const Anthropic = require('@anthropic-ai/sdk');
const { createClient } = require('@supabase/supabase-js');

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SECRET);

const ATHLETE_PROFILE = `Kerim, 22 ans, gaucher, étudiant BA1 Sciences Motricité EPS ULB Bruxelles.
Sports: cyclo-cross (principal), handball (secondaire). Niveau connexion corps-esprit: DÉBUTANT.
Conditions: TDAH, hyperlaxité ligamentaire, phénotype Marfan-like.
Blessures: subluxation épaule gauche (oct 2024), fracture poignet gauche (nov 2021),
fractures fatigue genoux (2018+2022), fissure tibia + double œdème genou droit (nov 2024),
exostose genou droit (déc 2025). Objectif: stabilité épaule gauche + retour sport complet.`;

// 50 topics par agent — 5 rounds de 10
const ALL_TOPICS = {
  kine: [
    'protocole rééducation subluxation gléno-humérale conservateur Bankart',
    'renforcement coiffe rotateurs hyperlaxe : infraépineux sous-scapulaire petit rond',
    'progression proprioception stable→instable→charge→distraction cognitive',
    'fractures fatigue stades Fredericson : critères retour sport objectifs',
    'TDAH rééducation : séances 20min max feedback sensoriel immédiat',
    'exercices excentriques tendinopathie vs repos total : mécanisme',
    'stabilisation scapulaire : trapèze inférieur et dentelé antérieur priorité',
    'connexion corps-esprit débutant : techniques conscience corporelle progressive',
    'gestion douleur chronique épaule chez sportif 22 ans',
    'retour cyclo-cross post subluxation épaule : critères fonctionnels',
    'mobilisation Maitland grade I-IV épaule : protocole progressif',
    'DNS Dynamic Neuromuscular Stabilization : activation stabilisateurs profonds',
    'chaîne postérieure épaule : capsule postérieure et subluxation récidivante',
    'test appréhension épaule : interprétation et suivi longitudinal',
    'hyperlaxité Beighton 6/9 : implications programme rééducation complet',
    'co-contraction avant force : ordre de priorité absolu chez hyperlaxe',
    'exostose genou droit : adaptation activités et indications chirurgicales',
    'œdème genou chronique : drainage lymphatique et compression progressive',
    'fracture poignet gauche ancienne : compensations biomécaniques à corriger',
    'bilan fonctionnel épaule : Hawkins Neer Jobe Empty Can interprétation',
    'programme domicile 10 min : adhérence maximale patient TDAH',
    'visualisation mentale pré-séance : protocole 2 min ancrage sensoriel',
    'retour handball post subluxation épaule : timeline semaine par semaine',
    'prévention récidive subluxation : programme maintenance long terme',
    'élastiques TheraBand progressions couleurs renforcement épaule',
    'synchronisation respiration et mouvement en rééducation proprioceptive',
    'douleur référée épaule : distinguer cervicale C5-C6 vs pathologie locale',
    'cryothérapie vs chaleur épaule : protocole selon phase inflammatoire',
    'double blessure épaule + genou simultanée : priorisation rééducation',
    'nutrition cicatrisation tissus mous : collagène 10g vitamine C timing',
    'sommeil récupération : impact TDAH sur qualité et rééducation',
    'stress académique douleur chronique : lien psychosomatique étudiant sport',
    'séance type 20 min rééducation épaule TDAH : structure bloc par bloc',
    'exercices unilatéraux bras gauche : compensations et précautions',
    'proprioception debout yeux fermés : progression 4 semaines protocole',
    'natation thérapeutique épaule : nages autorisées et contre-indiquées',
    'vélo stationnaire pendant rééducation épaule : bénéfices et posture',
    'retour musculation après rééducation : ordre introduction exercices',
    'test fonctionnel retour sport : 5 critères objectifs avant autorisation',
    'port sac étudiant : adaptations posturales et conseils ergonomiques',
    'récupération active vs passive entre séances rééducation',
    'motivation intrinsèque rééducation : techniques coaching patient TDAH',
    'tendinopathie sus-épineux : diagnostic différentiel et protocole',
    'mobilité thoracique cycliste : hypercyphose et impact épaule',
    'bilan 3 mois subluxation : critères progression ou stagnation',
    'peur du mouvement kinésiophobie : approche graduelle exposition',
    'programme rééducation 12 semaines complet épaule : phases détaillées',
    'douleur à 3h du matin épaule : causes et signification clinique',
    'gainage hypopressif vs classique pour athlète hyperlaxe',
    'travail informatique et épaule : ergonomie poste étude ULB adaptation',
  ],
  hand: [
    'biomécanique tir suspension gaucher : impulsion pied droit élan genou gauche',
    'armé coude 100° minimum gaucher : erreur bras seul sans rotation tronc',
    'libération balle avant point le plus haut : timing optimal gaucher',
    'rotation tronc droite→gauche dans l air : dissociation bassin épaules',
    'prévention tendinopathie épaule lanceur gauche : protocole hebdomadaire',
    'hyperlaxité épaule gauche handball : stabilisation active avant chaque tir',
    'système défensif 6-0 : ligne contact épaule pivot jambe intérieure',
    '7vs6 : timing passe déplacement synchronisé balle plus rapide que jambes',
    'TDAH handball terrain : un seul signal tactique par possession',
    'tir en pivot gaucher : protection balle rotation corps et timing',
    'règle IHF 2026 : headshot 2min passive play throw-off accéléré',
    'défense 5+1 : rôle défenseur avancé lecture passe lobée déclencheur',
    'échauffement épaule handball : 8 exercices coiffe avant entraînement',
    'progression débutant connexion corps-esprit vers tir technique phases',
    'tir en appui gaucher : appui pied droit poussée jambe transfert énergie',
    'feinte de tir gaucher : déclenchement défenseur timing vrai tir',
    'jeu de jambes attaque : changement direction premier pas explosif gaucher',
    'passe longue gaucher : rotation épaule snap poignet timing',
    'montée balle 1c1 gaucher : dribble protégé côté dominant',
    'contre-attaque 3c2 : lecture situation décision passe ou tir gaucher',
    'puissance vs précision tir : compromis distance gardien positionnement',
    'récupération épaule lanceur après match : protocole 48h complet',
    'force excentrique épaule handball : exercices prévention spécifiques',
    'coordination œil-main lancer précision : drills progressifs gaucher',
    'tir à 9m gaucher : angle optimal zone visée coin bas loin',
    'tir en course gaucher : synchronisation foulée et armé',
    'pénalty handball gaucher : préparation mentale technique exécution',
    'supériorité numérique 6c5 : circulation balle création espace',
    'analyse biomécanique Gidsel tir : points transférables gaucher',
    'hyperlaxité genoux handball : réception et changements direction sécurisés',
    'proprioception cheville handball : prévention entorses récidivantes',
    'séance technique 90min structure : échauffement technique tactique match',
    'feedback après tir raté : méthode sandwich adapté TDAH',
    'visualisation mentale avant pénalty : protocole 30 secondes',
    'stress compétition handball : routine pré-match gaucher 15 min',
    'cyclo-cross vers handball : transfert puissance jambes coordination',
    'nutrition avant match handball : timing repas et choix glucides',
    'blessures fréquentes handball : doigts épaule genou cheville prévention',
    'retour compétition post subluxation épaule : décision médicale sportive',
    'niveau débutant connexion corps-esprit bras : exercices proprioception',
    'objectif 6 mois handball débutant : jalons réalistes techniques',
    'préparation physique pré-saison handball : 6 semaines programme type',
    'analyse vidéo propre tir : 5 points techniques observables corriger',
    'communication terrain handball : signaux vocaux gestuels codés',
    'double entraînement jour handball : récupération épaule entre sessions',
    'test Cooper handball : niveaux référence et objectifs amélioration',
    'défense sur dribbleur rapide : pieds écartés regard poitrine',
    'attaque contre bloc 6-0 : percer intérieur ou tir extérieur',
    'placement aile gauche attaque : timing appel et réception balle',
    'programme estival sans club handball : maintien 8 semaines',
  ],
  muscu: [
    'ratio tirages poussées 2:1 épaule fragile post subluxation',
    'hyperlaxité muscu : stabilisation avant charges lourdes ordre exercices',
    'push-up progression avant bench press épaule fragilisée',
    'périodisation off-season cyclo-cross : force max puis puissance explosive',
    'RIR reps in reserve pour débutant connexion corps-esprit',
    'jamais lockout complet extension coude genou hyperlaxité',
    'gainage fonctionnel cyclo-cross : anti-rotation prioritaire dead bug',
    'tempo excentrique 3s descente : bénéfices hypertrophie et tendon',
    'déload détection surmenage athlète TDAH : signaux et protocole',
    'reconstruction genou post fractures fatigue : exercices accessoires',
    'squat goblet débutant : apprentissage mouvement connexion corps-esprit',
    'Romanian deadlift : activation ischio-fessiers proprioception chaîne',
    'tirage horizontal : trapèze inférieur dentelé angle et technique',
    'face pull : coiffe rotateurs et correction posture enroulée cycliste',
    'exercices unilatéraux : correction asymétrie bras gauche dominant',
    'progression planche abdominale : genou instable charge progressive',
    'hip thrust puissance glutes : transfert cyclo-cross et handball',
    'nordic curl ischio : prévention protocole progressif débutant',
    'rotation externe épaule élastique : exercice quotidien maintien',
    'presse jambes vs squat : choix genou fragile fractures fatigue',
    'programme 3j/semaine débutant : push pull legs adapté profil',
    'progression charges hebdomadaire : 2.5kg upper 5kg lower réaliste',
    'échauffement 10min muscu : mobilité dynamique spécifique',
    'activation pré-lift : band pull apart face pull fessiers',
    'DOMS distinguer bonne douleur vs signal blessure',
    'nutrition peri-workout : glucides avant protéines glucides après',
    'suivi progression : tableau 1RM estimé volume sensation effort',
    'respiration Valsalva vs continue : quand chaque méthode',
    'force maximale vs endurance force : méthodes et objectifs',
    'périodisation ondulante : variation charge volume semaine par semaine',
    'test force 5RM calculé : protocole sécurité débutant',
    'étirements post-muscu : statique 30s priorité hanches épaules',
    'prévention tendinite rotulienne : excentrique quadriceps protocole',
    'foam roller utilisation : pré et post séance zones prioritaires',
    'programme 6 semaines débutant complet : semaine par semaine détail',
    'adaptation période examens : volume -40% intensité maintenue',
    'transfert muscu cyclo-cross : puissance spécifique pédalage',
    'objectifs réalistes 6 mois débutant : gains force hypertrophie',
    'stabilisation lombaire avant soulevé : transverse abdomen activation',
    'mobilité thoracique avant pressing : exercices 5 min préparation',
    'gainage latéral anti-rotation : Copenhagen plank et variantes',
    'programme maison élastiques : progressions résistance sans salle',
    'débutant miroir feedback : conscience corporelle position correcte',
    'charge mentale TDAH et musculation : structure courte claire',
    'double sport charges muscu : intégration semaine handball cyclo',
    'récupération active entre sets : mobilité vs repos passif',
    'renforcement genou 360° : extension flexion rotation stabilité',
    'évaluation posturale avant programme : identification compensations',
    'adaptation charge selon sommeil et stress : autoregulation TDAH',
    'force de préhension : importance performance sport collectif',
  ],
  mobilite: [
    'hyperlaxité mobilité passive excessive vs contrôle actif insuffisant',
    'CAR épaule quotidien 2 min matin : protocole tissu conjonctif',
    'PAILs RAILs épaule position fermée avant ouverte progression',
    'étirements passifs contre-indiqués hyperlaxe : mécanisme aggravation',
    'mobilité hanche 90-90 cycliste handballeur : technique durée',
    'respiration mobilité thoracique : quadrupède inspiration latérale',
    'FRC vs yoga classique athlète hyperlaxe : pourquoi FRC supérieur',
    'end-range training : renforcer contrôle fin de course articulaire',
    'mobilité cheville post fractures fatigue : protocole 8 semaines',
    'mobilité intégrée échauffement handball cyclo-cross 10 min',
    'CARs hanches : rotation complète active sans compensation lombaire',
    'CARs thoracique : dissociation vertèbre par vertèbre erreurs',
    'test mobilité active vs passive épaule : interpréter différence',
    'mobilité poignet gauche post fracture : exercices progressifs',
    'genou valgus dynamique : mobilité hanche cheville comme cause',
    'mobilité cheville dorsiflexion : test mur valeurs normales correction',
    'rotation interne hanche : test FABER FADIR lien lombalgie cycliste',
    'extension thoracique foam roller : technique fréquence recommandée',
    'mobilité côtés latéroflexion thoracolombaire pour cycliste courbé',
    'stretch ischio actif vs passif : lequel choisir hyperlaxe',
    'mobilité épaule plan scapulaire : différence plan frontal implications',
    'capsule postérieure épaule : sleeper stretch précautions hyperlaxe',
    'Kinstretch 20 min : structure séance type athlète polyvalent',
    'mobilité cervicale : rotation inclinaison lien épaule vision',
    'pieds mobilité cheville : impact sur toute chaîne cinétique',
    'respiration diaphragmatique : technique apprentissage intégration sport',
    'test Thomas hanche : psoas court et programme correction',
    'mobilité genou flexion : mesure et amélioration post blessure',
    'mobilité + force intégrée : exercices combinés hyperlaxe',
    'mobilité avant entraînement : dynamique uniquement jamais statique',
    'mobilité après entraînement : statique profond 30-60s récupération',
    'TDAH mobilité : séance 10 min max 3 exercices feedback tactile',
    'mobilité spécifique vélo : hanches rotation interne extension thoracique',
    'mobilité spécifique handball : rotation thoracique élévation épaule',
    'routine mobilité matin 10 min : protocole hyperlaxe quotidien',
    'compensation lombaire : identifier substitution hanche ou thoracique',
    'stabilité proximale avant mobilité distale : principe hyperlaxe',
    'exostose genou mobilité : exercices autorisés contre-indiqués',
    'double séance sport + mobilité : placement optimal dans semaine',
    'progrès mobilité : timeline 3 mois 6 mois 12 mois réaliste',
    'irradiation tension FRC : principe et application pratique',
    'scapula mobilité : rythme scapulo-huméral et dyskinésie correction',
    'activation matin 5 min CARs : routine complète bien démarrer',
    'collagène supplémentation mobilité : timing et tissu conjonctif',
    'stress rigidité musculaire : examens TDAH et programme mobilité',
    'objectifs mobilité 6 mois : métriques mesurables jalons concrets',
    'Kelly Starrett principes : concepts clés adaptés hyperlaxe',
    'bilan mobilité complet : 15 tests valeurs référence athlète',
    'rotation interne épaule : mesure goniomètre et programme amélioration',
    'mobilité intégrée jeu handball : positions défense attaque spécifiques',
  ],
  foot: [
    'tir pied gauche appui 30-40cm genou au dessus balle contact cheville verrouillée',
    'follow-through axe cible rotation hanche interne tir gaucher',
    'passe longue gaucher : rotation tronc différence vs droitier mécanique',
    'pressing PPDA trigger passe en arrière shadow pressing orientation corps',
    'Nordic hamstring football : -51% récidive ischio protocole progressif',
    'transition attaque-défense 4 secondes organisation collective',
    'TDAH terrain foot : un signal tactique par action maximum',
    'hyperlaxité sprint football : cheville genou surveillance strapping',
    'PAPE activation neuro avant match : protocole échauffement',
    'ailier gaucher inverti : mouvements coupés intérieur création',
    'centre depuis gauche : cross gaucher ras terre et lobé technique',
    'tir en course gaucher : synchronisation foulée et frappe',
    'corner donneur gaucher : effet intérieur extérieur technique',
    'coup franc gaucher : mur cheville trajectoire courbe',
    'contre-attaque : lecture situation accélération décision',
    'passes filtrées entre lignes : lecture espace timing déclencheur',
    'accélération 10m explosivité spécifique football',
    'prévention entorse cheville : proprioception plateau instable',
    'récupération post match : protocole 48h jeune athlète complet',
    'double sport cyclo-cross football : gestion charge hebdomadaire',
    'nutrition avant match : repas type 3h avant coup de sifflet',
    'analyse vidéo performance : 5 points techniques clés observer',
    'travail technique individuel 30 min : structure session efficace',
    'jeu sans ballon gaucher : appels décrochages superpositions',
    'tir en pivot gaucher : protection balle défenseur timing',
    'duel aérien gaucher : timing saut placement corps',
    'remise jeu latérale gaucher : technique distance maximale',
    'gestion physique mi-temps : récupération active 15 min protocole',
    'analyse xG : comprendre améliorer qualité des tirs',
    'blocage tir : positionnement corps timing saut défenseur',
    'positionnement ailier gauche : espaces appels profondeur',
    'dribble vitesse gaucher : protection balle côté dominant',
    'leadership jeune joueur : prise décision sous pression',
    'test Yo-Yo intermittent : interprétation et objectifs',
    'endurance spécifique foot : fractionné 4x4 min protocole',
    'force explosive jambes sprint tir : exercices clés',
    'proprioception monopodale foot : progression 4 semaines',
    'récupération mentale après défaite : reset émotionnel',
    'montée balle pression haute : protection et relance',
    'pressing individuel 1v1 : angle approche et timing pied',
    'finition une touche gaucher : placement corps et timing',
    'communication défensive : appels et organisation collective',
    'préparation physique pré-saison 6 semaines : programme type',
    'retour terrain post blessure genou : critères fonctionnels',
    'programme estival sans club : maintien condition 8 semaines',
    'stress compétition : routine pré-match 10 min mental',
    'objectifs saisonniers réalistes gaucher polyvalent',
    'nutrition récupération post match : fenêtre optimale',
    'placement équipe hors balle : structure bloc défensif',
    'cyclo-cross vers football : transfert cardio et différences',
  ],
  basket: [
    'mécanique tir gaucher BEEF adapté balance eyes elbow follow',
    'loading jambes tir gaucher : flexion 90-120° transfert vertical',
    'release sommet saut : timing pronation poignet gaucher',
    'coude intérieur tir : alignement correction erreur commune',
    'lecture pick and roll : hard hedge drop switch selon situation',
    'défense individuelle stance low wide : pieds regard mains',
    'RFD basketball : force max plyométrie même séance transfert',
    'TDAH basket : signal unique par possession feedback immédiat',
    'prévention cheville : plyométrie progressive protocole semaines',
    'dribble main gauche dominante : amélioration main droite isolation',
    'floater gaucher : coordination foulées et touch doux finition',
    'step-back jumper gaucher : créer espace équilibre tir',
    'euro-step gaucher : légalité 2 foulées et technique',
    'pull-up jumper arrêt gaucher : freinage équilibre immédiat',
    'contre-attaque 2c1 : décision passe ou finir gaucher',
    'drive baseline gaucher : angle et finitions ambidextre',
    'mid-range pull up : zones tir efficaces gaucher',
    'pénétration kick-out : lecture défense timing passe',
    'rebond offensif : positionnement anticipation tip-in gaucher',
    'transition défensive : sprint retour organisation collective',
    'post-up gaucher : technique entrée dos panier pivot',
    'catch and shoot gaucher : préparation avant réception',
    'tir 3pts gaucher : fréquence zones prioritaires entraînement',
    'isolation 1c1 gaucher : lecture défenseur prise décision',
    'force mentale compétition : routine avant-match protocole',
    'analyse vidéo tir : 5 points techniques observer corriger',
    'récupération entre matchs basket 48h protocole complet',
    'endurance spécifique basket : intermittent 15-15 Billat',
    'hyperlaxité basket : réceptions changements direction sécurisés',
    'épaule gauche basket : gestes autorisés précautions match',
    'communication défensive : appels switch help ball',
    'nutrition game day basket : repas timing choix',
    'stretch routine post match basket 10 min priorités',
    'objectifs saison débutant basket : métriques 6 mois',
    'transfert cyclo-cross basket : endurance aérobie différences',
    'TDAH compétition basket : focus 40 minutes stratégies',
    'confiance au tir : rebuild après passage à vide protocole',
    'blessures fréquentes basket : doigts genoux chevilles',
    'retour basket post blessure épaule : critères progression',
    'double sport handball basket : gestion conflits mouvements',
    'arbitrage règles FIBA 2026 : nouveautés importantes',
    'travail mains sans ballon : 15 exercices quotidiens',
    'structure semaine entraînement basket : répartition intensités',
    'tir en mouvement vs arrêté : priorité développement gaucher',
    'lecture jeu vision périphérique : exercices développement',
    'récupération mentale mauvaise performance : reset protocole',
    'programme estival sans coach : maintien condition 8 semaines',
    'screening offensif illégal vs légal : règle et technique',
    'force relative basket : développement saut vertical gaucher',
    'coéquipiers chemistry : communication confiance collective',
  ],
  natation: [
    'high elbow catch crawl : avant-bras vertical prise eau efficace',
    'rotation épaule précède traction : timing erreur commune',
    'hyperlaxité natation : accrochage épaule crawl prévention',
    'stabilisation coiffe avant séance natation élastiques protocole',
    'virage culbute : appui 1.5m rotation bloc extension complète',
    'respiration crawl : expire complète eau inspire explosive',
    'gainage anti-rotation nageur : dead bug side plank',
    'entrée main 11h 1h : jamais axe médian cause zigzag',
    'battements 6 temps économie vs 2 temps vitesse',
    'TDAH natation : routine fixe entrée eau focus unique longueur',
    'départ plongeon : réaction déclenchement position vol entrée',
    'bras papillon : catch symétrique ondulation corps synchronisé',
    'dos crawlé : rotation corps 45° entrée petit doigt',
    'brasse : coup jambes timing et coordination complète',
    'nage endurance vs sprint : adaptation technique selon vitesse',
    'splits 25m analyse : identifier zones perte vitesse',
    'récupération bras aérien crawl : coude haut relâchement',
    'poussée murale départ : angles genoux hanches optimaux',
    'coordination bras jambes crawl : synchronisation débutant',
    'respiration bilatérale : bénéfices et apprentissage',
    'pull buoy isolation jambes : renforcement haut corps',
    'palmes apprentissage : aide technique renforcement chevilles',
    'planche jambes : correction battements alignement',
    'résistance eau : parachute élastique résistant exercices',
    'endurance fond 1500m : gestion allure mental nageur',
    'sprint 50m : mobilisation maximale technique vitesse',
    'série lactate 8x100m : protocole interprétation résultats',
    'récupération après natation : retour calme 10 min',
    'épaule nageur syndrome : prévention renforcement 3x/semaine',
    'mobilité épaules natation vs hyperlaxité : programme adapté',
    'analyse vidéo sous-marine : 5 points techniques clés',
    'nutrition piscine : collation avant après séance',
    'organisation semaine 4 séances : répartition intensités',
    'natation thérapeutique épaule : nages autorisées post subluxation',
    'stress eau TDAH : relaxation avant mise à l eau',
    'objectifs natation 6 mois débutant : temps réalistes',
    'transfert cyclo-cross natation : endurance cardio différences',
    'double entraînement natation handball : séquence optimale',
    'compétition natation : échauffement 45 min avant départ',
    'récupération mentale mauvaise course : reset protocole',
    'chlore peau cheveux : protection soins post piscine',
    'sécurité eau : règles fondamentales gestion urgences',
    'bilan nageur : test Cooper natation niveaux référence',
    'hyperlaxité cheville natation : battements amplitude contrôle',
    'programme 12 semaines débutant : vers intermédiaire',
    'matériel nageur essentiel : lunettes bonnet palmes pull buoy',
    'préparation compétition : affûtage 2 semaines avant',
    'natation eau libre vs piscine : adaptations techniques',
    'communication coach nageur : feedback constructif TDAH',
    'prévention otite sinusite : hygiène régulière nageur',
  ],
  gym: [
    'ATR appui tendu renversé : ligne parfaite mains épaules hanches pieds',
    'gainage actif ATR : pousser sol activer épaules stabilisation',
    'rondade conversion élan horizontal vers vertical mécanique',
    'flic-flac arrière : vol timing réception mains au sol',
    'réception 3 temps cheville genou hanche : jamais valgus',
    'hyperlaxité gym co-contraction avant tous sauts protocole',
    'code FIG 2025 score E dominant : priorité exécution difficulté',
    'prévention poignets gymnaste : renforcement progressif appui',
    'TDAH gym : rituel séance identique micro-objectifs éléments',
    'connexion corps-esprit ATR débutant : étapes progressives',
    'roue gymnaste : alignement latéral placement mains pieds',
    'pont arrière : mobilité thoracique épaules prérequis',
    'salto avant groupé sol : prérequis sécurité et progression',
    'flip arrière : impulsion verticale timing bras',
    'rondade-flic-flac enchaînement : connexion et élan maintenu',
    'sol gym : musique chorégraphie technique simultanément',
    'éléments poutre : équilibre concentration micro-ajustements',
    'anneaux débutant : gainage total et appuis stables',
    'barres parallèles : balancement passage sol',
    'barre fixe : tour appel élan roulade arrière',
    'force relative gymnaste : ratio force poids objectifs',
    'souplesse fonctionnelle gym vs hyperlaxité : différence approche',
    'prévention dos gymnaste : chaîne postérieure et mobilité',
    'prévention chevilles gym : proprioception et renforcement',
    'visualisation mentale avant passage : protocole 2 min',
    'stress compétition gym : routine pré-passage gestion peur',
    'nutrition gymnaste : poids de forme performance équilibre sain',
    'récupération après entraînement intense gym 24h',
    'hyperlaxité réception : absorption choc stabilisation active',
    'coaching positif gym TDAH : feedback constructif encouragement',
    'progression éléments par difficulté : grille évolution',
    'analyse vidéo gym : 3 points de vue commentaires techniques',
    'gainage profond transverse avant tous éléments',
    'placement épaules gym : rétraction dépression scapulaire',
    'tapis réception : zones sécurisées techniques chute',
    'pareur gym : protocole aide sécurisée nouveaux éléments',
    'mental gym après chute : protocole retour confiance',
    'programme annuel gym : macrocycle compétition préparation',
    'combinaisons éléments : connexion valorisation code FIG',
    'camp entraînement intensif gym : gestion volume récupération',
    'évaluation élèves gym : critères techniques FIG adaptés',
    'proprioception pieds nus gym : bénéfices exercices',
    'échauffement gymnaste : mobilité épaules poignets chevilles dos',
    'transfert cyclo-cross gym : équilibre conscience corporelle',
    'objectifs gym 6 mois débutant : éléments réalistes',
    'double entraînement gym : récupération charge totale',
    'force saut vertical gymnaste : développement plyométrie',
    'prévention genoux gymnaste : renforcement et réception',
    'rotation corps dans l air : conscience spatiale développement',
    'rythme éléments acrobatiques : sens musicaux et chorégraphie',
  ],
  course: [
    'attaque médio-pied : différence talon freinage et pointe surcharge',
    'cadence optimale 170-180 pas/min : comment atteindre progressivement',
    'entraînement polarisé 80-20 Seiler : application pratique',
    'progression volume 10%/semaine max : prévention fractures fatigue',
    'cyclo-cross vers course : transfert endurance et différences clés',
    'zones entraînement Z1-Z5 : FCmax et perception effort',
    'gainage lombaire coureur : dead bug anti-rotation spécifique',
    'Pose method : pose-fall-pull et stride trop long erreur',
    'TDAH running : routine pré-sortie objectif unique par séance',
    'retour course post fissure tibia : protocole progressif',
    'temps de contact sol : minimiser 200ms élite amateur',
    'inclinaison avant 2-3° : posture optimale et économie course',
    'bras en L rigide : rôle équilibre et économie énergétique',
    'fractionné 30-30 Billat : protocole VO2max développement',
    'seuil lactate : identifier et entraîner zone 3 spécifiquement',
    'récupération active post course longue : marche 10 min',
    'étirements post-course : statiques profonds zones prioritaires',
    'chaussures drop 8mm minimum post fracture fatigue',
    'nutrition trail long : ravitaillement solide liquide timing',
    'hydratation course : 500ml heure et signaux soif',
    'entraînement croisé : natation vélo pendant récupération course',
    'test VO2max terrain : Cooper 12 min et interprétation',
    'semaine type coureur débutant : répartition 3 sorties',
    'dénivelé et économie course montée descente : techniques',
    'hyperlaxité cheville course : proprioception et strapping',
    'surveillance GPS données : cadence fréquence cardiaque bilan',
    'préparation 10km débutant : plan 8 semaines progressif',
    'récupération après compétition : protocole 72h post effort',
    'double sport cyclo-cross course : synergie et différences charge',
    'prévention syndrome bandelette IT : causes et exercices correction',
    'renforcement quadriceps : prévention genou coureur protocole',
    'activation fessiers avant course : 5 exercices 5 min',
    'analyse foulée vidéo : 5 points techniques observables',
    'progression débutant connexion corps-esprit course',
    'motivation long terme running : objectifs intermédiaires TDAH',
    'stress course : mental avant première compétition',
    'nutrition course courte vs longue : glucides et timing',
    'bilan énergétique hebdo coureur : apports selon volume',
    'programme 12 semaines 5km débutant : semaine par semaine',
    'retour course après subluxation épaule : adaptations balancement',
    'course en côte : bénéfices et technique montée',
    'intervalles courts 200m-400m : vitesse et forme technique',
    'récupération sommeil coureur : importance 8h pour adaptation',
    'objectifs réalistes 6 mois débutant : temps et volume',
    'transfert handball course : endurance collective vs individuelle',
    'prévention tendinite Achille : excentrique mollet protocole',
    'entraînement par perception effort : RPE et avantages',
    'analyse fractures fatigue historique : facteurs récidive éviter',
    'prévention fasciite plantaire : causes et correction',
    'foulée sprint vs course endurance : différences techniques fondamentales',
  ],
  volley: [
    'smash gaucher approche 3 pas miroir : droite-gauche-droite impulsion',
    'bras frappeur gaucher : arc de cercle épaule-coude-poignet-main',
    'prono-supination fin geste topspin gaucher : contact et suivi',
    'service float 2026 : frappe sèche centre gravité trajectoire imprévisible',
    'réception 2 joueurs libero : communication codée avant chaque service',
    'plyométrie verticale : box jumps depth jumps protocole 2x/semaine',
    'prévention épaule frappeur gauche : coiffe 2x/semaine obligatoire',
    'TDAH volley : signal unique par rotation feedback après échange',
    'hyperlaxité smash : stabilisation active épaule gauche avant armé',
    'transition défense-attaque : timing appel après réception qualité',
    'contre au filet gaucher : timing saut et placement mains',
    'manchette réception haute qualité : placement pieds et absorption',
    'passe en manchette longue : rotation épaules et impulsion jambes',
    'touche libero spécifique : positionnement lecture service adverse',
    'attaque dos au filet gaucher : pivot et frappe timing',
    'smash pipe milieu : prise d élan et tempo frappe',
    'défense en dive : technique chute controlée et récupération',
    'service à la main gauche puissant : élan et contact précis',
    'rotation volley : positions et responsabilités chaque rotation',
    'lecture setter : anticiper destination balle avant frappe',
    'blocage individuel vs collectif : lecture et timing saut',
    'freeball : attaque intelligente vs coup direct',
    'communication attaquants : appels tempo et placement',
    'échauffement spécifique volley : épaules genoux chevilles',
    'analyse vidéo smash : 5 points techniques clés gaucher',
    'récupération post match volley 48h : protocole complet',
    'nutrition avant match volley : timing et choix repas',
    'force explosive verticale : objectifs et progression plyométrie',
    'proprioception cheville volley : prévention entorses',
    'double sport handball volley : transfert et conflits techniques',
    'test détente verticale : progression et objectifs gaucher',
    'tempo d attaque : 1er temps 2e temps 3e temps lecture',
    'set sur passe difficile : adaptation frappe et angle',
    'prise de risque au service : agressivité vs sécurité',
    'préparation physique pré-saison volley 6 semaines',
    'stress compétition volley : routine service rituel mental',
    'objectifs 6 mois gaucher débutant volley : jalons réalistes',
    'règles volley 2026 : nouvelles règles et applications',
    'travail réception 1000 balles : structure séance qualité',
    'renforcement genou volley : atterrissage et prevention',
    'cyclo-cross vers volley : transfert cardio et différences',
    'programme été volley sans club : maintien 8 semaines',
    'leadership volley : communication capitaine et cohésion',
    'concentration entre les points : routines 15 secondes',
    'variété attaques : gamme complete tirs et feintes',
    'évaluation technique smash : grille observation objective',
    'retour volley post blessure épaule : progression étapes',
    'chaleur et performance volley : hydratation et adaptation',
    'partenaire entraînement : exercices 2c2 développement',
    'équipe mixte vs homogène : adaptations tactiques',
  ],
  athle: [
    'phase accélération sprint : inclinaison 45° poussée vers arrière',
    'cycle jambe actif : shin angle et contact sol minimal',
    'saut en longueur : appel pied plat fouetté de pied en vol',
    'haies : enjamber pas sauter -0.15s mauvaise technique',
    'fractures fatigue : protocole retour ≤10% volume/semaine',
    'hyperlaxité sprint : surveillance tibio-fibulaire cheville',
    'strapping prophylactique cheville : entraînement intense',
    'TDAH athlétisme : focus unique par répétition rituel départ',
    'plyométrie post fracture fatigue : progression très graduelle',
    'transfert cyclo-cross sprint : puissance aérobie différences',
    'vitesse maximale sprint 60-80m : cycle jambe actif et contact',
    'départ blocks : réaction angle tibia position mains',
    'phase transition accélération vers vitesse : changements mécaniques',
    'sprint 400m : gestion allure et glycolyse anaérobie',
    'haies 110m hommes : rythme 3 appuis entre obstacles',
    'saut en hauteur Fosbury : courbe d élan et passage barre',
    'triple saut : cloche-pied-pas-saut ratio et technique',
    'vitesse de réaction : entraînement temps de réaction 0.12s',
    'force explosive sprint : demi-squat et plyométrie transfert',
    'endurance spécifique 800m : VMA et protocole entraînement',
    'récupération entre séances sprint : 48-72h SNC',
    'analyse vidéo sprint : plan sagittal frontal points clés',
    'prévention ischio sprint : nordic curl et excentrique',
    'chaussures spikes : impact biomécanique et adaptation progressive',
    'test VMA : navette ou piste interprétation et objectifs',
    'compétition athlétisme : échauffement protocol et timing',
    'stress compétition : routine pré-épreuve mental et physique',
    'nutrition avant compétition athlétisme : timing et choix',
    'cyclo-cross vers haies : endurance transfert et coordination',
    'foulée sprint et course : différences techniques fondamentales',
    'objectifs 6 mois débutant athlétisme : performances réalistes',
    'double sport handball athlétisme : gestion charge et synergies',
    'programme hiver athlétisme : piste couverte vs extérieur',
    'préparation physique athlète polyvalent : base foncière',
    'bilan biomécanique sprint : points forts faibles et priorités',
    'récupération mentale après disqualification ou chute',
    'leadership équipe relais : communication et passation bâton',
    'gainage athlète sprint : anti-rotation et stabilité dynamique',
    'mobilité hanche sprint : rotation interne et extension active',
    'force relative sprint : ratio poids et puissance optimale',
    'entraînement collines : bénéfices spécifiques et technique',
    'détente verticale vs horizontale : ratio optimal sprinteur',
    'périodisation saison athlétisme : prépa foncière spécifique comp',
    'prévention fasciite plantaire : causes et exercices correction',
    'retour compétition post fracture fatigue : décision médicale',
    'entorse cheville post sprint : protocole retour et prévention',
    'alimentation piste : hydratation et énergie entre séries',
    'rotation interne hanche sprint : exercices mobilité spécifiques',
    'coordination bras sprint : L rigide et impulsion',
    'analyse film athlètes élite : points transférables profil gaucher',
  ],
  nutri: [
    'protéines 1.6-2.2g/kg/j : pas besoin dépasser pour athlète naturel',
    'collagène 10g + vit C à jeun avant entraînement : tissu conjonctif',
    'oméga-3 EPA+DHA 2-3g/j : TDAH concentration et récupération',
    'calcul TDEE 78kg 185cm 22ans : 3000-3200 kcal estimation',
    'timing post-effort : fenêtre 0-2h protéines glucides optimal',
    'période examens : pas restriction magnésium oméga-3 caféine',
    'double sport cyclo-cross handball : gestion énergie hebdo',
    'hydratation cycliste : 500ml/h minimum électrolytes si plus 1h',
    'repas pré-handball : glucides complexes 2-3h avant match',
    'récupération nuit : caséine avant dormir objectif force',
    'glucides entraînement : 3-5g/kg/j modéré 6-10g/kg/j intense',
    'lipides minimum 20% calories : hormones et santé globale',
    'vitamine D supplémentation : 2000UI/j athlète indoor Belgique',
    'magnésium 300-400mg/j : crampes TDAH stress et sommeil',
    'créatine 3g/j : bénéfices force et récupération athlète 22 ans',
    'caféine 3-6mg/kg pré-entraînement : protocole et tolérance',
    'bilan martial fer ferritine : risque cycliste et coureur',
    'zinc et immunité : importance athlète double sport',
    'timing glucides avant cyclo-cross : 90g/h effort plus 90 min',
    'hydratation poids avant après : calcul pertes sudation',
    'boissons énergétiques vs eau : recommandations selon durée',
    'récupération musculaire : ratio glucides protéines 3:1 post effort',
    'nutrition pendant compétition : gels barres timing pratique',
    'jeûne intermittent et sport : contre-indications pour athlète actif',
    'végétarisme et performance : sources protéines alternatives',
    'alcool et récupération : impact sur synthèse protéique',
    'anti-inflammatoires naturels : curcuma gingembre cerise protocole',
    'probiotiques immunité athlète : souches et dosages efficaces',
    'stress oxydatif entraînement : antioxydants timing optimal',
    'poids de forme cyclo-cross : composition corporelle et performance',
    'alimentation pré-saison : prise masse maigre protocole',
    'nutrition période blessure : adapter apports sans déconditionnement',
    'réhydratation post effort : électrolytes et vitesse absorption',
    'collation pré-entraînement 1h avant : choix et quantités',
    'dîner récupération après match tard : composition et timing',
    'petit déjeuner sportif matin entraînement : structure type',
    'suppléments légaux WADA 2026 : liste et recommandations',
    'bêta-alanine tamponnage lactate : protocole charge et maintenance',
    'HMB et récupération musculaire : utilisation chez blessé',
    'vitamines B complexe et énergie : rôle et sources alimentaires',
    'gut microbiome et performance : alimentation diversifiée fibre',
    'récupération post subluxation épaule : nutrition spécifique',
    'programme nutrition 4 semaines débutant : structure pratique',
    'analyse composition corporelle : DEXA vs impédancemétrie',
    'phosphatidylsérine stress cortisol : supplémentation athlète',
    'alimentation exam + entraînement : équilibre cognitif physique',
    'objectifs nutritionnels 6 mois : métriques et suivi',
    'consultation diététicien sport : quand et pourquoi utile',
    'iode et thyroïde athlète : importance souvent négligée',
    'glucides index glycémique faible : avant effort prolongé cyclo',
  ],
};

const AGENTS = [
  { key: 'kine',     name: 'Marc Revel',          role: 'kinésithérapeute du sport élite' },
  { key: 'hand',     name: 'Stefan Kovač',         role: 'coach handball élite' },
  { key: 'muscu',    name: 'Alexandre Petit',      role: 'coach renforcement musculaire' },
  { key: 'mobilite', name: 'Dr. Kenji Watanabe',   role: 'expert mobilité fonctionnelle FRC' },
  { key: 'foot',     name: 'Marco Delgado',        role: 'coach football élite' },
  { key: 'basket',   name: 'Tony Reeves',          role: 'coach basketball élite' },
  { key: 'natation', name: 'Claire Fontaine',      role: 'coach natation élite' },
  { key: 'gym',      name: 'Isabelle Marchetti',   role: 'coach gymnastique artistique' },
  { key: 'course',   name: 'Julien Marais',        role: 'coach course à pied élite' },
  { key: 'volley',   name: 'Marco Benedetti',      role: 'coach volleyball élite' },
  { key: 'athle',    name: 'Dr. Amara Diallo',     role: 'coach athlétisme élite' },
  { key: 'nutri',    name: 'Dr. Léa Rousseau',     role: 'nutritionniste sport élite' },
];

// Génère les mémoires pour UN round (10 topics par agent)
async function generateRound(roundIndex) {
  const start = roundIndex * 10;
  const end = start + 10;
  const results = [];

  for (const agent of AGENTS) {
    const topics = ALL_TOPICS[agent.key].slice(start, end);
    const memories = [];

    // Générer les 10 topics de ce round en parallèle
    const responses = await Promise.allSettled(topics.map(topic =>
      client.messages.create({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 250,
        messages: [{
          role: 'user',
          content: `Tu es ${agent.name}, ${agent.role}.
Athlète cible : ${ATHLETE_PROFILE}
Sujet : "${topic}"

Génère UN cas coaching synthétique court. JSON UNIQUEMENT :
{"cas":"2-3 phrases décrivant un cas réel rencontré avec ce type d'athlète","regle":"règle clé apprise (1 phrase actionnable)","score":9}`
        }]
      }).then(r => {
        const text = r.content.filter(b => b.type === 'text').map(b => b.text).join('');
        return JSON.parse(text.replace(/```json|```/g, '').trim());
      })
    ));

    for (const r of responses) {
      if (r.status === 'fulfilled') {
        memories.push({
          agent: agent.key,
          learned: `[EXP] ${r.value.cas}`,
          rule: r.value.regle,
          score: r.value.score || 9
        });
      }
    }

    // Insérer en batch Supabase
    if (memories.length > 0) {
      await supabase.from('agent_memories').insert(memories);
    }
    results.push({ agent: agent.key, count: memories.length });
  }
  return results;
}

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const auth = req.headers.authorization;
  if (auth !== 'Bearer apex-train-2026') return res.status(401).json({ error: 'Non autorisé' });

  // round = 0..4 (5 rounds de 10 topics chacun = 50 par agent)
  const round = parseInt(req.query.round || req.body?.round || '0');
  if (round < 0 || round > 4) return res.status(400).json({ error: 'Round invalide (0-4)' });

  const startTime = Date.now();
  try {
    const results = await generateRound(round);
    const total = results.reduce((s, r) => s + r.count, 0);
    const duration = ((Date.now() - startTime) / 1000).toFixed(1);
    res.status(200).json({
      success: true,
      round,
      total,
      duration,
      details: results,
      nextRound: round < 4 ? round + 1 : null,
      done: round === 4
    });
  } catch(err) {
    res.status(500).json({ error: err.message, round });
  }
};
